### ISSUE TITLE
Where are steps 2 to 4 from Bedrock installation implemented?

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#11]
https://roots.io/bedrock/docs/installing-bedrock/

**Comment by elghazal-a** [comment]
Step 2: Copy .env.example to .env and update environment variables
 Though .env.example is copied automatically by Bedrock to .env, I dont need to update vars inside it because I inject environment variables in wordpress container at runtime. those variables injected take precedence over vars declared in .env

Step 3: Add theme(s) in web/app/themes as you would for a normal WordPress site
I don't add any theme yet. I'm working on installing SAGE theme.

Step 4: Set your site vhost document root to /path/to/site/web/
This is done in nginx configuration that will route traffic to the app (not yet pushed)

I hope that answers the question
