### ISSUE TITLE
?? Queries

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#21]
01. Which Linux folders are shared between the containers and the EC2 linux host?

02. Which Linux folders are shared between the containers and the Windows host?

03. Which folders from inside containers are publically accessible through Apache? Laravel, Bedrock - What folder path each framework is publishing through Apache?

Which folders can a possible "hack" visitor "browse" (view) by manipulating the browser's URL?

04. Which port mappings are configured between containers and the host?

05. Which ports are exposed to the Web from the host? For which reason?

06. Which users and groups the EC2 host has configured? What permissions each user and group has? Which folder each user / group has permissions and which are these permissions?

07. Which users and groups are configured on each of the containers? What permissions each user / group has? Which folder each user / group has permissions and which are these permissions?

08. Which network protocols (ports) are exported from the EC2 host to the web? For which reason?

10. Can you enable SSH access to the EC2 host?

11. Is it difficult to configure https://help.ubuntu.com/lts/serverguide/ftp-server.html#vsftpd-ftp-server-installation on the EC2 host? You need to create a separate user for FTP access? Please allow the ftp user to browse all folders starting from the root /

Note* - The intention is (using FTP clients) to allow browsing, in production, of the bedrock / laravel PHP app source code / logs and I assumed the FTP server should be installed on the EC2 host (or the containers should run the FTP server?)

12. Which is the command to stop all running containers from my Windows machine?

13. Instructions to stop all containers on the AWS host?

14. Instructions to stop / clean everything on AWS environment (so that $$$ charges will be 0 after the environment will be stopped / cleared).

15. Instructions / commands / steps to re-provision "from scratch" everything on AWS - assuming I stopped everything as per previous Step 13 and I need to re-provision the same app again? Repeated re-provisions should work reliable (for instance on local windows machine running multiple times setup was failing and you showed me to use -p $unique_name like a docker namespace - if something similar will be required when re-provisioning on AWS please document everything needed to safely provision-clear-everything-reprovision-again multiple times reliably)

16. Let's say in few months an existing project (using these scripts) will accumulate PHP code (inside bedrock app or inside laravel) and the code will be hosted on github. At some point I will do git clone to an existing empty Windows folder and I will want to run "provision.sh" to setup a new AWS cloud deployment (with the PHP code available at that time). Which are the steps to do this? Is this anything special I will need to do for re-provisioning an existing app to AWS? This kind of repeated setup / provisions executions should work reliable on both WIndows and AWS (i.e. tricks like -p $unique_name should be documented)

17. Support for Amazon RDS

With the current code what steps are required to do in order to connect to an Amazon RDS database instead of using the current docker my_sql image?

Ideally 

* in development (setup) the current docker mysql image should be default but it should be possible to configure connection to an Amazon RDS instead (if Amazon RDS will be configured by developer instead of docker mysql - maybe to debug / test a scenario on real production data)
* in production (provisioning) it should be the other way around - Amazon RDS should be default but it should be possible to configure connection to the current docker mysql image if this is what the developer will want

18. What happens if I will forget and I will run with APP_INIT=yes repeatedly? I could break / lose my existing "work" source code? (this should not happen even If I forget and I run by mistake again with APP_INIT=yes)

19. Related with previous query #18 can we totally eliminate these 2 variables from our setup?

~~WP_INIT=yes~~
~~PROJECT_PATH=C:\Projects\wordpress-laravel-docker-local-cloud-aws2\work~~

Instead of "work" we will provide an empty folder called **"app"** (you can put an empty text file inside - sometimes git has difficulties with empty folders) - This folder app will be a sibling of the folder setup (next to setup - on the same level)

Put a simple logic inside the setup script to check and see if there exists a folder named ../app/bedrock ==> If so it means the setup was already executed ==> Do Nothing and Otherwise if you cannot find any ../app/bedrock ==> It means it is the first time we execute setup ==> continue and run the full setup

This way we will not need ~~WP_INIT~~ or ~~PROJECT_PATH~~

**Comment by elghazal-a** [comment]
1- No folder is shared between the containers and the EC2 linux host
https://github.com/distributev/wordpress-laravel-docker-local-cloud/issues/30#issuecomment-369052261

2- In the dev host, 2 volumes are shared
* ${PROJECT_PATH} is mounted into bedrock_sage_lara, sage_builder and laravel_builder containers
* wordpress-mysql is mounted into mysql container. This volume is managed by Docker and is located under `/var/lib/docker`

3- /var/www/html/bedrock/web (bedrock) and /var/www/html/laravel/public (laravel) are publically accessible through Apache

4- Port mapping configured can be found in docker-compose under `ports` section
* ${MYSQL_PORT}:${MYSQL_PORT}
* 9000:8080
* ${APACHE_PORT}:${APACHE_PORT}
* 3000:3000
* 3001:3001

5- 
* ${APACHE_PORT}: Apache port that render all php files
* 3000: BrowserSync that reload css/js files in browser
* 3001: BrowserSync UI

6- 
* root: full acess
* ubuntu: it come up with ubuntu AMI. It's a sudoer and has full access when using sudo
* dokku: created automatically when installing Dokku. used to manage dokku. it has full access only to /home/dokku

7- The image we build from Dockerfile has the following users
* root
* www-data: the owner of /var/wwww

8- the ports exported are
* 80: used by nginx. Nginx is configured to forward to request to Apache that render bedrock and ralavel php files
* 9000: adminer
* 22: ssh

9- SSH access is already enabled in the EC2

10- #30

12- `docker stop $(docker ps -q)`

13- In EC2, you can stop all containers with the same command `docker stop $(docker ps -q)`. However, containers are running using Dokku and it's better to manage containers using Dokku cli rather than Docker cli
* ssh to EC2
* swicth to dokku user with `sudo su -l dokku`
* `dokku apps:help` to see available commands to manage apps. dokku provide rich cli to manage apps, better to check the doc

14- `terraform destroy`. Must be run within `cloud-aws` folder

15- 
You can easily re-provision everything from scratch
destroy the infra with `terraform destroy`
create everything with `terraform apply`
If you just want to recreate your app after destroying it. You have to run manually the commands in provision.sh for app creation and configuration
https://github.com/distributev/wordpress-laravel-docker-local-cloud/blob/master/provisioning/cloud-aws/provision.sh#L45


16- Provisioning and deployment are 2 separated steps. boths steps are documented
AWS resources provisioning is handled by Terraform
Dokku installation and app configuration code is written in provision.sh and executed by AWS
Deployment is handled by developer

provision.sh is (and can be) executed only one time when booting the EC2 for the first time. It's not used for repeated configuration. For example, you can't use provision.sh to install later other thing. If you update provision.sh and apply the change with Terraform, Terraform will destroy the current EC2 and create new EC2 provisioned by the new provision.sh

17- will be done in #29

18- done
19- done
