### ISSUE TITLE
Laravel really needs to wait for WordPress to start?

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#24]
![image](https://user-images.githubusercontent.com/19224635/36717324-eb249bc0-1b9d-11e8-99b7-618dda7ab849.png)

**Comment by elghazal-a** [comment]
I want you to understand the purpose of the different services we run in docker-compose

1- `wordpress`: maybe the name is misleading, but this is the main service, it run everything (bedrock + sage + laravel + apache). this service generate all the stacks using composer when wp_init=yes. Apache serves bedrock, sage and laravel php files.

2- `sage`: this service watch css/js/ts files and build (compilation, transpile,..) them. 
3- `laravel`: this service watch css/js/ts files and build (compilation, transpile,..) them. 

I added `sage` and `laravel` services for developer convenience. Instead of manually running build command, thoses services will watch files and automatically build. Thoses services are used only in development. 

Let's get back to your question now. I want to make sure that I start `sage` and `laravel` when sage and laravel files are already generated by composer and all dependencies are installed (otherwise, they will fail to start). Hence, I decided to wait for `wordpress` (Apache) service to start. In fact, Apache will start after all installation commands succeeds.
I hope it does answer your question

**Comment by distributev** [comment]
Yes it answers the question somehow but maybe then we can find service names better aligned with their purpose.

Though I'm not sure which is the best solution 

- now we have the service name based on the WP component (it makes sense from this perspective) but it fails short when it displays "Laravel waiting for WordPress" - this message is misleading here because Laravel is for sure not waiting for WP here
- but also if we go the other route and we will give the service a more "technical or developer friendly name" to satisfy our technical dependencies and make developer logs more accurate ==> in that case we will finish with a more cryptic (and less functionally obvious) service name

**Comment by elghazal-a** [comment]
Yeah I agree with you, I suggest the following

* we rename all the services
    * `wordpress` to `bedrock_sage_lara`
    * `sage` to `sage_builder`
    * `laravel` to `laravel_builder`
* we rename the waiting messages like this `waiting for Laravel/Sage installation...`

**Comment by distributev** [comment]
Yes this naming is good for services.

But the folder names should be called based on the components we use  as described here - https://github.com/distributev/wordpress-laravel-docker-local-cloud/issues/22
