### ISSUE TITLE
Local development and cloud provisioned environments should be identical

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#27]
Don't use different files and scripts for development. All our scripts in development and in production should be identical and we should not need .dev versions of the scripts like this one

![image](https://user-images.githubusercontent.com/19224635/36718996-10eea0d4-1ba4-11e8-86f2-65c1f8826d19.png)

**Comment by elghazal-a** [comment]
Environments are similar as much as possible since both they run on the same base docker images. We can even enhance that by grouping the common code in Dockerfile and Dockerfile.dev in the same base image. For example the code that install composer, nodejs , wp-cli can be stored in custom base image that will be maintained separately and pushed to Docker Hub for example. this will remove repetitive code.

The main reason why we can't use the same Dockerfile for both environments is that your development environment focus more in generating the project than running the project. the environments focus on two different purposes

The good thing is that you can run **locally** your app in environment 100% similar of production using the Dockerfile.
```
docker build -t prod/bedrock . #this command will build an image similar to the one running in production
docker run --rm -P prod/bedrock #run your image and test it
```

**Comment by distributev** [comment]
Yes group as much as possible common code in Dockerfile.common and then have Dockerfile.dev reuse Dockerfile.common + dev specific stuff and Dockerfile.prod  reuse Dockerfile.common + prod specific stuff

This way it will be obvious what is common and dev and prod specific parts will also become clear.

**Comment by elghazal-a** [comment]
Actually Docker doesn't support using Dockerfile inside Dockerfile, but Docker can build Dockerfile starting from custom Docker image using `FROM`.
So Dockerfile.dev and Dockerfile.prod will use docker image built from Dockerfile.commun. Where do you want to store this docker image?

**Comment by sourcekraft** [comment]
Is it possible to achieve something similar using appropriate well targeted .sh shell script files? As you said currently Dockerfile.dev and Dockerfile contain "copy-pasted" code and this is what I want to resolve now (and not necessary to separate docker images). If you'll find a way to avoid this "copy-paste" and reuse appropriate well targeted shell scripts this will be good enough for me. When I read dockerfile.dev I should clearly see what code is common what is specific to dev and the same for prod.

**Comment by distributev** [comment]
Can you achieve a similar logical separation using well defined separate shell scripts? I'm not necessary interested to make separate docker images for this but, as you said, the two docker files currently contain "copy pasted" code and I need this situation improved. When I will open dockerfiles.dev I should easily note the common code (shell scripts) and then I should easily spot the "dev" specific scripts - and the same with dockerfiles.prod I should easily see the separation between common code and prod specific commands.
