### ISSUE TITLE
Allow FTP connections

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#30]
Is it difficult to configure https://help.ubuntu.com/lts/serverguide/ftp-server.html#vsftpd-ftp-server-installation on the EC2 host? You need to create a separate user for FTP access? The ftp user should be allowed to browse all folders starting from the root /

Note* - The intention is, using FTP clients programs, to allow browsing in production of the bedrock / laravel PHP app source code / logs. I believe an FTP server should be installed on the EC2 host for that.

**Comment by elghazal-a** [comment]
It's not difficult to configure ftp. However, I don't recommend you that. The main purpose of ftp is to transfer file between your machine and the server. As of now, you have Dokku as paas that can make you deploy code with a single command.
If you only need to browse content, the simple and secure way is to ssh to the server (ssh is already installed and configured).

Even if you installed ftp in the server, you wont be able to browse your source code. Your code is run inside Docker container. if you want to browse your code, your need to ssh to the server and get inside your container.

Anyways, if you want to do DevOps, you don't have to browse the code running in production. you shouldn't debug in production. Besides, you can run in your local the same docker container running in production and debug comfortably.

Let me know if you still believe you need FTP server and I'll implement it

**Comment by distributev** [comment]
Yes you are right only git pushes should be used to modify anything on production. 

I'm not very fast with ssh and linux commands and just browsing in a read only mode for anything it could be a real (and slow) pain. Is there a better way to quickly visualize the file system in a read-only way something similar with Windows Explorer? Maybe I'll need to check some log files but not only that. FTP was the first thing which came to me.

EC2 host will have the PHP source code shared with the containers similar with how the Windows host is sharing the project folder so at least the project code should be brow-sable directly on the EC2 host. Isn't it so?

**Comment by elghazal-a** [comment]
For me the best way to read file content is through ssh, maybe there some other nice alternatives that I ignore.

I agree with you, you will need to check log files. According to my experience, most of the time you will need to check logs using `tail` command to output the last logs and wait for the new logs. You can get this feature only when connecting to server using ssh

We don't share code volume in production, it's not like in dev environment where you need to change code. In production, the code is packaged in docker image. 
The way Docker stores images is little bit complex due to the design of image. Each image consists of a series of layers. Docker makes use of union file systems to combine these layers into a single image. Union file systems allow files and directories of separate file systems, known as branches, to be transparently overlaid, forming a single coherent file system. So the short answer is, it's not possible to read your code from the host.

**Comment by distributev** [comment]
OK - fine. I'll stick to ssh then.
