### ISSUE TITLE
Browser console should be error free for both Sage and Laravel

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#46]
![image](https://user-images.githubusercontent.com/19224635/36889261-8c747132-1df9-11e8-9a67-c2efc245ca10.png)

**Comment by elghazal-a** [comment]
This 404 error is expected. To the best of my knowledge, when using browsersync+webpack, they delete main.css and inject it via javascript.
By the way, you should use the server opened by browsersync instead of apache. Anyways, developers should know more about that than me
learn more about this issue here https://discourse.roots.io/t/sage-9-main-css-404-on-devurl/9799/9
