### ISSUE TITLE
EVERYTHING IS UP AND RUNNING is not accurate

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#53]
Please see below screenshot.

**_Is it OK if additional commands are coming after EVERYTHING IS UP AND RUNNING?_** - Can I be sure that once I see EVERYTHING IS UP AND RUNNING everything is indeed ready?

![image](https://user-images.githubusercontent.com/19224635/36970635-86d5ac06-2069-11e8-8860-8ff77e6f073e.png)

**Comment by elghazal-a** [comment]
Actually I log `EVERYTHING IS UP AND RUNNING` right before Apache is started. I can't log anything else after Apache started. So you will always see Apache logs after `EVERYTHING IS UP AND RUNNING` log.

In screenshot, I see also browsersync and webpack logs because you asked docker-compose to show all containers logs. You can filter that and show only bedrock_sage_lara logs using `docker-compose logs -f bedrock_sage_lara`. However, you will always see Apache logs after `EVERYTHING IS UP AND RUNNING` log.

**Comment by distributev** [comment]
OK.
