### ISSUE TITLE
Hardcodings

### ISSUE THREAD

**Issue by distributev** [distributev/wordpress-laravel-docker-local-cloud#58]
![image](https://user-images.githubusercontent.com/19224635/37286409-2487a916-2602-11e8-8cea-faf634313087.png)

**Comment by elghazal-a** [comment]
Regarding the line `ENV APP_PATH /var/www/wordpress`, I changed to `ENV APP_PATH /tmp/app` in my last commit 36dabdb69b8bd46c6a6b4aa167628b9d54e6dc8d, I needed to copy the project and install the dependencies in a temporary folder in the build time, and move the contents of that folder to `/var/www/html` in the runtime. The reason why I did this workaround is too technical to explain, but it's mainly due to this line of code https://github.com/docker-library/wordpress/blob/master/php7.2/apache/Dockerfile#L44

Wordpress team expects that we share wordpress data from the host and mount it in `/var/html/www` of the container. In our case, we installed wordpress in the build time using composer (thanks to bedrock). 

This is why I used the folder `/var/www/wordpress` in the first place, but since you wanted to keep the default path (#41), I had to do this workaround
